### ISSUE TITLE
Evaluate Results

### ISSUE THREAD

**Issue by HannesOberreiter** [chrishah/AMEB2020_Phylogenomics_demo#4]
Hi,

found probably a "good" ID to test against.

**ID**: EOG090X002Z
**Paralog Count**: [2]
**My Result**: [1]

If I look at all results for this ID I get following picture, which should result in [1] in my opinion because we only have one complete entry:
![image](https://user-images.githubusercontent.com/16878981/83255132-28db5400-a1b0-11ea-9468-d4fbae096662.png)

All my results:
[results.txt](https://github.com/chrishah/AMEB2020_Phylogenomics_demo/files/4701531/results.txt)

My vanilla R Script (`Rscript --vanilla ../../bin/evaluate-alt.r`) if you are interested, careful for in- and outgroup it takes the taxa from filename and not folder (eg. A_coleoptrata).
https://www.dropbox.com/s/2kmz4u27ayj5vul/evaluate-alt.r?dl=0

Maybe I have next week some time left over, then I check your python script why this is happening and if my code is wrong or yours.

Cheers
Hannes

**Comment by chrishah** [comment]
Hi Hannes,

You are right. It should be [1]. I will have to doublecheck my code. Thanks for spotting that!!!

cheers,
Christoph

**Comment by chrishah** [comment]
Hi,
Think I found and fixed the problem in the python script - see commit -[f24d95ac18ffd9fe39d97f24efaa6c86adfdb338](https://github.com/chrishah/AMEB2020_Phylogenomics_demo/commit/f24d95ac18ffd9fe39d97f24efaa6c86adfdb338)

Want to rerun everything after that now, because the set of genes for which I need to do the trees has changed now and I want to make sure all is fine. Stay tuned!

Thanks again!
cheers,
Christoph

**Comment by HannesOberreiter** [comment]
Closing as bug is fixed with commit: f24d95ac18ffd9fe39d97f24efaa6c86adfdb338
